name: CI

on: [push, pull_request]

jobs:
  build-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["16", "18", "20", "22"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        NODE_VERSION: ${{ matrix.node_version }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      run: bash build-image.sh
