name: CI

on: [push, pull_request]

jobs:
  build-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["18"]
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Login to Aliyun Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
    
    - name: Login to Private Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.PRIVATE_REPOSITORY }}
        username: ${{ secrets.PRIVATE_REPOSITORY_USERNAME }}
        password: ${{ secrets.PRIVATE_REPOSITORY_PASSWORD }}
    
    - name: Build the Docker image
      env:
        NODE_VERSION: ${{ matrix.node_version }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        PRIVATE_REPOSITORY: ${{ secrets.PRIVATE_REPOSITORY }}
        PRIVATE_REPOSITORY_USERNAME: ${{ secrets.PRIVATE_REPOSITORY_USERNAME }}
        PRIVATE_REPOSITORY_PASSWORD: ${{ secrets.PRIVATE_REPOSITORY_PASSWORD }}
      run: bash build-image.sh
